"""Randomly generated weird words list
many thanks to https://randomwordgenerator.com/weird-word.php
"""

weird_words = [
    'solferino',
    'pullet',
    'balneology',
    'decumbent',
    'kurtosis',
    'delignate',
    'venesect',
    'cyanotype',
    'tiro',
    'nuciferous',
    'pellicle',
    'iroko',
    'unipara',
    'ignavia',
    'adventitious',
    'overset',
    'resistentialism',
    'venter',
    'conferva',
    'pelitic',
    'lustrum',
    'ploce',
    'anta',
    'subarrhation',
    'poecilomere',
    'wis',
    'diffident',
    'acerous',
    'agronomics',
    'supererogation',
    'latten',
    'dompteuse',
    'clarigate',
    'empaestic',
    'hierophant',
    'gladiate',
    'brindled',
    'anthropotheism',
    'catenular',
    'affabulation',
    'vesper',
    'lecithal',
    'chiffon',
    'diegesis',
    'philotherianism',
    'brocard',
    'theotechny',
    'aerography',
    'lavabo',
    'fusee',
    'queenite',
    'viminal',
    'rugate',
    'pudor',
    'sphygmograph',
    'aerobiology',
    'calcariferous',
    'isomagnetic',
    'zemindar',
    'mor',
    'accipitrine',
    'gynaecocracy',
    'oenophile',
    'irremoval',
    'empennage',
    'feckless',
    'cnemis',
    'hadeharia',
    'bastion',
    'gambado']


"""
This ASCII Art was
generated by ASCII Art Generator
https://patorjk.com/software/taag/#p=display&f=Rectangles&t=Welcome
"""
welcome_banner = '''                               
    _ _ _     _                   
    | | | |___| |___ ___ _____ ___ 
    | | | | -_| |  _| . |     | -_|
    |_____|___|_|___|___|_|_|_|___|
                                '''